[build]
  command = "echo 'Skipping npm install to avoid plugin conflicts' && mkdir -p node_modules"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
